version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: notification-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notificationdb
    volumes:
      - notification-mongo-data:/data/db
volumes:
  notification-mongo-data:
