version: '3.8'

services:
  # PostgreSQL Database for Order Service
  postgres:
    image: postgres:15-alpine
    container_name: order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    networks:
      - order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - Database Management UI (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: order-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    networks:
      - order-network
    depends_on:
      - postgres

volumes:
  order-postgres-data:
    driver: local

networks:
  order-network:
    driver: bridge
