spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # Don't register itself as a client
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Disable self-preservation mode in development
    enable-self-preservation: false
    # How often to evict expired instances
    eviction-interval-timer-in-ms: 5000
    # Response cache update interval
    response-cache-update-interval-ms: 5000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,eureka
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application Info
info:
  app:
    name: Eureka Service Discovery Server
    description: Netflix Eureka Server for microservice registration and discovery
    version: 1.0.0
    developer: Vyshali
