# Common Configuration for All Services
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Actuator Configuration (Common)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration (Common)
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Common Feature Flags
features:
  maintenance-mode: false
  debug-mode: false
